// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RikiPath.Infrastructure;

#nullable disable

namespace RikiPath.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924090853_ChangeEmailNullable")]
    partial class ChangeEmailNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RikiPath.Domain.Entities.AiCreditTopUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PaymentTransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PaymentStatus");

                    b.ToTable("AiCreditTopUps");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.CertificationLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CertificationId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CertificationId", "Code")
                        .IsUnique();

                    b.ToTable("CertificationLevels");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.CertificationLevelSkill", b =>
                {
                    b.Property<int>("CertificationLevelId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("CertificationLevelId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("CertificationLevelSkills");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultantAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsultantId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConsultantId", "StartTime", "EndTime");

                    b.ToTable("ConsultantAvailabilities");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultationAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ConsultantId")
                        .HasColumnType("integer");

                    b.Property<int>("ConsultationRequestId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MeetingNotes")
                        .HasColumnType("text");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConsultantId");

                    b.HasIndex("ConsultationRequestId")
                        .IsUnique();

                    b.ToTable("ConsultationAnswers");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultationPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("ConsultationPackages");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultationPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ConsultationPackageId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PaymentTransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationPackageId");

                    b.HasIndex("UserId");

                    b.ToTable("ConsultationPurchases");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ConsultantAvailabilityId")
                        .HasColumnType("integer");

                    b.Property<int?>("ConsultantId")
                        .HasColumnType("integer");

                    b.Property<int>("ConsultationPurchaseId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MeetingLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultantAvailabilityId")
                        .IsUnique();

                    b.HasIndex("ConsultationPurchaseId")
                        .IsUnique();

                    b.HasIndex("ConsultantId", "Status");

                    b.ToTable("ConsultationRequests");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.EmailVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerifications");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.GradingResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FeedbackJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GradedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("OverallScore")
                        .HasColumnType("double precision");

                    b.Property<int>("PracticeSubmissionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PracticeSubmissionId")
                        .IsUnique();

                    b.ToTable("GradingResults");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.GrammarPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CertificationLevelId")
                        .HasColumnType("integer");

                    b.Property<int>("ContentAuthorId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ExampleSentence")
                        .HasColumnType("text");

                    b.Property<string>("ExampleSentenceMeaning")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<string>("ReviewedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Structure")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("UsageNotes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContentAuthorId");

                    b.HasIndex("CertificationLevelId", "Status");

                    b.ToTable("GrammarPoints");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.KanjiEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<int>("CertificationLevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("ContentAuthorId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("KunYomi")
                        .HasColumnType("text");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OnYomi")
                        .HasColumnType("text");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<string>("ReviewedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SinoVietnamese")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StrokeCount")
                        .HasColumnType("integer");

                    b.Property<string>("StrokeOrderImageUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContentAuthorId");

                    b.HasIndex("CertificationLevelId", "Status");

                    b.ToTable("KanjiEntries");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.LearningPathSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsViewed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SuggestionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "GeneratedAt");

                    b.ToTable("LearningPathSuggestions");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CertificationLevelId")
                        .HasColumnType("integer");

                    b.Property<int>("ContentAuthorId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<string>("ReviewedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContentAuthorId");

                    b.HasIndex("SkillId");

                    b.HasIndex("CertificationLevelId", "SkillId", "Status");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.LessonGrammar", b =>
                {
                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("GrammarPointId")
                        .HasColumnType("integer");

                    b.HasKey("LessonId", "GrammarPointId");

                    b.HasIndex("GrammarPointId");

                    b.ToTable("LessonGrammars");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.LessonKanji", b =>
                {
                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("KanjiEntryId")
                        .HasColumnType("integer");

                    b.HasKey("LessonId", "KanjiEntryId");

                    b.HasIndex("KanjiEntryId");

                    b.ToTable("LessonKanjis");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.LessonProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LastPositionSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastWatchedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId", "LessonId")
                        .IsUnique();

                    b.ToTable("LessonProgresses");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.LessonVocabulary", b =>
                {
                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("VocabularyEntryId")
                        .HasColumnType("integer");

                    b.HasKey("LessonId", "VocabularyEntryId");

                    b.HasIndex("VocabularyEntryId");

                    b.ToTable("LessonVocabularies");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PracticeTestSectionId")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PracticeTestSectionId");

                    b.ToTable("PracticeQuestions");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeQuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PracticeQuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PracticeQuestionId");

                    b.ToTable("PracticeQuestionOptions");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CertificationLevelId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TextContent")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CertificationLevelId");

                    b.HasIndex("UserId", "Type", "SubmittedAt");

                    b.ToTable("PracticeSubmissions");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CertificationLevelId")
                        .HasColumnType("integer");

                    b.Property<int>("ContentAuthorId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<string>("ReviewedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TimeLimitMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("ContentAuthorId");

                    b.HasIndex("CertificationLevelId", "Status");

                    b.ToTable("PracticeTests");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTestAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PracticeQuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("PracticeTestAttemptId")
                        .HasColumnType("integer");

                    b.Property<int?>("SelectedOptionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PracticeQuestionId");

                    b.HasIndex("SelectedOptionId");

                    b.HasIndex("PracticeTestAttemptId", "PracticeQuestionId")
                        .IsUnique();

                    b.ToTable("PracticeTestAnswers");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTestAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PracticeTestId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("TotalScore")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PracticeTestId");

                    b.HasIndex("UserId", "PracticeTestId");

                    b.ToTable("PracticeTestAttempts");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTestSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PracticeTestId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("PracticeTestId");

                    b.HasIndex("SkillId");

                    b.ToTable("PracticeTestSections");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTestSectionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PracticeTestAttemptId")
                        .HasColumnType("integer");

                    b.Property<int>("PracticeTestSectionId")
                        .HasColumnType("integer");

                    b.Property<double>("ScorePercent")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PracticeTestSectionId");

                    b.HasIndex("PracticeTestAttemptId", "PracticeTestSectionId")
                        .IsUnique();

                    b.ToTable("PracticeTestSectionResults");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ReviewItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("EaseFactor")
                        .HasColumnType("double precision");

                    b.Property<int?>("GrammarPointId")
                        .HasColumnType("integer");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("KanjiEntryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NextReviewDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Repetitions")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("VocabularyNoteEntryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrammarPointId");

                    b.HasIndex("KanjiEntryId");

                    b.HasIndex("VocabularyNoteEntryId");

                    b.HasIndex("UserId", "NextReviewDate");

                    b.ToTable("ReviewItems");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ReviewLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Quality")
                        .HasColumnType("integer");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("ReviewItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReviewItemId");

                    b.ToTable("ReviewLogs");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AiGradingQuota")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrial")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<int>("DailyStudyMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("FirebaseUid")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastStudyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StudyTimePreference")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("SystemNotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("TargetCertificationLevelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TargetCertificationLevelId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AiGradingQuota")
                        .HasColumnType("integer");

                    b.Property<int>("AiGradingUsedCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PaymentTransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("UserId", "PaymentStatus", "EndDate");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.VocabularyEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<int>("CertificationLevelId")
                        .HasColumnType("integer");

                    b.Property<int>("ContentAuthorId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ExampleSentence")
                        .HasColumnType("text");

                    b.Property<string>("ExampleSentenceMeaning")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Reading")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<string>("ReviewedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ContentAuthorId");

                    b.HasIndex("CertificationLevelId", "Status");

                    b.ToTable("VocabularyEntries");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.VocabularyList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("VocabularyLists");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.VocabularyNoteEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("KanjiEntryId")
                        .HasColumnType("integer");

                    b.Property<string>("ManualMeaning")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ManualReading")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ManualWord")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int?>("VocabularyEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("VocabularyListId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KanjiEntryId");

                    b.HasIndex("VocabularyEntryId");

                    b.HasIndex("VocabularyListId");

                    b.ToTable("VocabularyNoteEntries");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.AiCreditTopUp", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("AiCreditTopUps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.CertificationLevel", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.Certification", "Certification")
                        .WithMany("Levels")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Certification");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.CertificationLevelSkill", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.CertificationLevel", "CertificationLevel")
                        .WithMany("Sections")
                        .HasForeignKey("CertificationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.Skill", "Skill")
                        .WithMany("CertificationLevelSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CertificationLevel");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultantAvailability", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "Consultant")
                        .WithMany("ConsultantAvailabilities")
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultant");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultationAnswer", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "Consultant")
                        .WithMany("ConsultationAnswers")
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.ConsultationRequest", "ConsultationRequest")
                        .WithOne("ConsultationAnswer")
                        .HasForeignKey("RikiPath.Domain.Entities.ConsultationAnswer", "ConsultationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultant");

                    b.Navigation("ConsultationRequest");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultationPurchase", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.ConsultationPackage", "ConsultationPackage")
                        .WithMany("Purchases")
                        .HasForeignKey("ConsultationPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("ConsultationPurchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConsultationPackage");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultationRequest", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.ConsultantAvailability", "ConsultantAvailability")
                        .WithOne("ConsultationRequest")
                        .HasForeignKey("RikiPath.Domain.Entities.ConsultationRequest", "ConsultantAvailabilityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "Consultant")
                        .WithMany("ConsultationRequestsAsConsultant")
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RikiPath.Domain.Entities.ConsultationPurchase", "ConsultationPurchase")
                        .WithOne("ConsultationRequest")
                        .HasForeignKey("RikiPath.Domain.Entities.ConsultationRequest", "ConsultationPurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultant");

                    b.Navigation("ConsultantAvailability");

                    b.Navigation("ConsultationPurchase");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.EmailVerification", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "User")
                        .WithMany("EmailVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.GradingResult", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.PracticeSubmission", "PracticeSubmission")
                        .WithOne("GradingResult")
                        .HasForeignKey("RikiPath.Domain.Entities.GradingResult", "PracticeSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticeSubmission");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.GrammarPoint", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.CertificationLevel", "CertificationLevel")
                        .WithMany("GrammarPoints")
                        .HasForeignKey("CertificationLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "ContentAuthor")
                        .WithMany("AuthoredGrammarPoints")
                        .HasForeignKey("ContentAuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CertificationLevel");

                    b.Navigation("ContentAuthor");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.KanjiEntry", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.CertificationLevel", "CertificationLevel")
                        .WithMany("KanjiEntries")
                        .HasForeignKey("CertificationLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "ContentAuthor")
                        .WithMany("AuthoredKanjiEntries")
                        .HasForeignKey("ContentAuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CertificationLevel");

                    b.Navigation("ContentAuthor");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.LearningPathSuggestion", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("LearningPathSuggestions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.CertificationLevel", "CertificationLevel")
                        .WithMany("Lessons")
                        .HasForeignKey("CertificationLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "ContentAuthor")
                        .WithMany("AuthoredLessons")
                        .HasForeignKey("ContentAuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.Skill", "Skill")
                        .WithMany("Lessons")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CertificationLevel");

                    b.Navigation("ContentAuthor");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.LessonGrammar", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.GrammarPoint", "GrammarPoint")
                        .WithMany("LessonGrammars")
                        .HasForeignKey("GrammarPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.Lesson", "Lesson")
                        .WithMany("LessonGrammars")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrammarPoint");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.LessonKanji", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.KanjiEntry", "KanjiEntry")
                        .WithMany("LessonKanjis")
                        .HasForeignKey("KanjiEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.Lesson", "Lesson")
                        .WithMany("LessonKanjis")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KanjiEntry");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.LessonProgress", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.Lesson", "Lesson")
                        .WithMany("LessonProgresses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("LessonProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.LessonVocabulary", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.Lesson", "Lesson")
                        .WithMany("LessonVocabularies")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.VocabularyEntry", "VocabularyEntry")
                        .WithMany("LessonVocabularies")
                        .HasForeignKey("VocabularyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("VocabularyEntry");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.Notification", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeQuestion", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.PracticeTestSection", "PracticeTestSection")
                        .WithMany("Questions")
                        .HasForeignKey("PracticeTestSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticeTestSection");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeQuestionOption", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.PracticeQuestion", "PracticeQuestion")
                        .WithMany("Options")
                        .HasForeignKey("PracticeQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticeQuestion");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeSubmission", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.CertificationLevel", "CertificationLevel")
                        .WithMany("PracticeSubmissions")
                        .HasForeignKey("CertificationLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("PracticeSubmissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CertificationLevel");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTest", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.CertificationLevel", "CertificationLevel")
                        .WithMany("PracticeTests")
                        .HasForeignKey("CertificationLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "ContentAuthor")
                        .WithMany("AuthoredPracticeTests")
                        .HasForeignKey("ContentAuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CertificationLevel");

                    b.Navigation("ContentAuthor");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTestAnswer", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.PracticeQuestion", "PracticeQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("PracticeQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.PracticeTestAttempt", "PracticeTestAttempt")
                        .WithMany("Answers")
                        .HasForeignKey("PracticeTestAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.PracticeQuestionOption", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PracticeQuestion");

                    b.Navigation("PracticeTestAttempt");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTestAttempt", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.PracticeTest", "PracticeTest")
                        .WithMany("Attempts")
                        .HasForeignKey("PracticeTestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("PracticeTestAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticeTest");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTestSection", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.PracticeTest", "PracticeTest")
                        .WithMany("Sections")
                        .HasForeignKey("PracticeTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.Skill", "Skill")
                        .WithMany("PracticeTestSections")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PracticeTest");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTestSectionResult", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.PracticeTestAttempt", "PracticeTestAttempt")
                        .WithMany("SectionResults")
                        .HasForeignKey("PracticeTestAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.PracticeTestSection", "PracticeTestSection")
                        .WithMany("SectionResults")
                        .HasForeignKey("PracticeTestSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PracticeTestAttempt");

                    b.Navigation("PracticeTestSection");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ReviewItem", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.GrammarPoint", "GrammarPoint")
                        .WithMany("ReviewItems")
                        .HasForeignKey("GrammarPointId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RikiPath.Domain.Entities.KanjiEntry", "KanjiEntry")
                        .WithMany("ReviewItems")
                        .HasForeignKey("KanjiEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("ReviewItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.VocabularyNoteEntry", "VocabularyNoteEntry")
                        .WithMany("ReviewItems")
                        .HasForeignKey("VocabularyNoteEntryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("GrammarPoint");

                    b.Navigation("KanjiEntry");

                    b.Navigation("UserAccount");

                    b.Navigation("VocabularyNoteEntry");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ReviewLog", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.ReviewItem", "ReviewItem")
                        .WithMany("ReviewLogs")
                        .HasForeignKey("ReviewItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewItem");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.UserAccount", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.CertificationLevel", "TargetCertificationLevel")
                        .WithMany("LearnersTargeting")
                        .HasForeignKey("TargetCertificationLevelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TargetCertificationLevel");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.UserSubscription", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.VocabularyEntry", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.CertificationLevel", "CertificationLevel")
                        .WithMany("VocabularyEntries")
                        .HasForeignKey("CertificationLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "ContentAuthor")
                        .WithMany("AuthoredVocabularyEntries")
                        .HasForeignKey("ContentAuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CertificationLevel");

                    b.Navigation("ContentAuthor");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.VocabularyList", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("VocabularyLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.VocabularyNoteEntry", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.KanjiEntry", "KanjiEntry")
                        .WithMany("VocabularyNoteEntries")
                        .HasForeignKey("KanjiEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RikiPath.Domain.Entities.VocabularyEntry", "VocabularyEntry")
                        .WithMany("VocabularyNoteEntries")
                        .HasForeignKey("VocabularyEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RikiPath.Domain.Entities.VocabularyList", "VocabularyList")
                        .WithMany("VocabularyNoteEntries")
                        .HasForeignKey("VocabularyListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KanjiEntry");

                    b.Navigation("VocabularyEntry");

                    b.Navigation("VocabularyList");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.Certification", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.CertificationLevel", b =>
                {
                    b.Navigation("GrammarPoints");

                    b.Navigation("KanjiEntries");

                    b.Navigation("LearnersTargeting");

                    b.Navigation("Lessons");

                    b.Navigation("PracticeSubmissions");

                    b.Navigation("PracticeTests");

                    b.Navigation("Sections");

                    b.Navigation("VocabularyEntries");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultantAvailability", b =>
                {
                    b.Navigation("ConsultationRequest");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultationPackage", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultationPurchase", b =>
                {
                    b.Navigation("ConsultationRequest");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultationRequest", b =>
                {
                    b.Navigation("ConsultationAnswer");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.GrammarPoint", b =>
                {
                    b.Navigation("LessonGrammars");

                    b.Navigation("ReviewItems");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.KanjiEntry", b =>
                {
                    b.Navigation("LessonKanjis");

                    b.Navigation("ReviewItems");

                    b.Navigation("VocabularyNoteEntries");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("LessonGrammars");

                    b.Navigation("LessonKanjis");

                    b.Navigation("LessonProgresses");

                    b.Navigation("LessonVocabularies");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeQuestion", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeSubmission", b =>
                {
                    b.Navigation("GradingResult");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTest", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTestAttempt", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("SectionResults");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTestSection", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("SectionResults");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ReviewItem", b =>
                {
                    b.Navigation("ReviewLogs");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.Skill", b =>
                {
                    b.Navigation("CertificationLevelSkills");

                    b.Navigation("Lessons");

                    b.Navigation("PracticeTestSections");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.UserAccount", b =>
                {
                    b.Navigation("AiCreditTopUps");

                    b.Navigation("AuthoredGrammarPoints");

                    b.Navigation("AuthoredKanjiEntries");

                    b.Navigation("AuthoredLessons");

                    b.Navigation("AuthoredPracticeTests");

                    b.Navigation("AuthoredVocabularyEntries");

                    b.Navigation("ConsultantAvailabilities");

                    b.Navigation("ConsultationAnswers");

                    b.Navigation("ConsultationPurchases");

                    b.Navigation("ConsultationRequestsAsConsultant");

                    b.Navigation("EmailVerifications");

                    b.Navigation("LearningPathSuggestions");

                    b.Navigation("LessonProgresses");

                    b.Navigation("Notifications");

                    b.Navigation("PracticeSubmissions");

                    b.Navigation("PracticeTestAttempts");

                    b.Navigation("ReviewItems");

                    b.Navigation("UserSubscriptions");

                    b.Navigation("VocabularyLists");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.VocabularyEntry", b =>
                {
                    b.Navigation("LessonVocabularies");

                    b.Navigation("VocabularyNoteEntries");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.VocabularyList", b =>
                {
                    b.Navigation("VocabularyNoteEntries");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.VocabularyNoteEntry", b =>
                {
                    b.Navigation("ReviewItems");
                });
#pragma warning restore 612, 618
        }
    }
}
