// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RikiPath.Infrastructure;

#nullable disable

namespace RikiPath.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultantAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsultantId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConsultantId", "StartTime", "EndTime");

                    b.ToTable("ConsultantAvailabilities");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultationAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ConsultantId")
                        .HasColumnType("integer");

                    b.Property<int>("ConsultationRequestId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MeetingNotes")
                        .HasColumnType("text");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConsultantId");

                    b.HasIndex("ConsultationRequestId")
                        .IsUnique();

                    b.ToTable("ConsultationAnswers");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultationPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("ConsultationPackages");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultationPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ConsultationPackageId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PaymentTransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationPackageId");

                    b.HasIndex("UserId");

                    b.ToTable("ConsultationPurchases");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ConsultantAvailabilityId")
                        .HasColumnType("integer");

                    b.Property<int?>("ConsultantId")
                        .HasColumnType("integer");

                    b.Property<int>("ConsultationPurchaseId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MeetingLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultantAvailabilityId")
                        .IsUnique();

                    b.HasIndex("ConsultationPurchaseId")
                        .IsUnique();

                    b.HasIndex("ConsultantId", "Status");

                    b.ToTable("ConsultationRequests");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContentAuthorId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseCategoryId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("JlptLevelId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<int?>("ReviewedById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("ContentAuthorId");

                    b.HasIndex("CourseCategoryId");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("JlptLevelId", "CourseCategoryId", "Status");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.CourseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CourseCategories");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.CoursePurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("numeric");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentTransactionId")
                        .HasColumnType("text");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("CoursePurchases");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.EmailVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerifications");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.GradingResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FeedbackJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GradedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("OverallScore")
                        .HasColumnType("double precision");

                    b.Property<int>("PracticeSubmissionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PracticeSubmissionId")
                        .IsUnique();

                    b.ToTable("GradingResults");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.GrammarPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContentAuthorId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ExampleSentence")
                        .HasColumnType("text");

                    b.Property<string>("ExampleSentenceMeaning")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("JlptLevelId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<int?>("ReviewedById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Structure")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("UsageNotes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContentAuthorId");

                    b.HasIndex("JlptLevelId");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("Title", "JlptLevelId");

                    b.ToTable("GrammarPoints");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.JlptLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("JlptLevels");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.KanjiEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("ContentAuthorId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("JlptLevelId")
                        .HasColumnType("integer");

                    b.Property<string>("KunYomi")
                        .HasColumnType("text");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OnYomi")
                        .HasColumnType("text");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<int?>("ReviewedById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SinoVietnamese")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StrokeCount")
                        .HasColumnType("integer");

                    b.Property<string>("StrokeOrderImageUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContentAuthorId");

                    b.HasIndex("JlptLevelId");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("Character", "JlptLevelId");

                    b.ToTable("KanjiEntries");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.LearningPathSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsViewed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SuggestionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "GeneratedAt");

                    b.ToTable("LearningPathSuggestions");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("CourseId", "SortOrder");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.LessonGrammar", b =>
                {
                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("GrammarPointId")
                        .HasColumnType("integer");

                    b.HasKey("LessonId", "GrammarPointId");

                    b.HasIndex("GrammarPointId");

                    b.ToTable("LessonGrammars");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.LessonKanji", b =>
                {
                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("KanjiEntryId")
                        .HasColumnType("integer");

                    b.HasKey("LessonId", "KanjiEntryId");

                    b.HasIndex("KanjiEntryId");

                    b.ToTable("LessonKanjis");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.LessonProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LastPositionSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastWatchedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId", "LessonId")
                        .IsUnique();

                    b.ToTable("LessonProgresses");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.LessonVocabulary", b =>
                {
                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("VocabularyEntryId")
                        .HasColumnType("integer");

                    b.HasKey("LessonId", "VocabularyEntryId");

                    b.HasIndex("VocabularyEntryId");

                    b.ToTable("LessonVocabularies");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PracticeTestSectionId")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PracticeTestSectionId");

                    b.ToTable("PracticeQuestions");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeQuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PracticeQuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PracticeQuestionId");

                    b.ToTable("PracticeQuestionOptions");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("JlptLevelId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TextContent")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JlptLevelId");

                    b.HasIndex("UserId", "Type", "SubmittedAt");

                    b.ToTable("PracticeSubmissions");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContentAuthorId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("JlptLevelId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<int?>("ReviewedById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TimeLimitMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("ContentAuthorId");

                    b.HasIndex("JlptLevelId");

                    b.HasIndex("ReviewedById");

                    b.ToTable("PracticeTests");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTestAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PracticeQuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("PracticeTestAttemptId")
                        .HasColumnType("integer");

                    b.Property<int?>("SelectedOptionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PracticeQuestionId");

                    b.HasIndex("SelectedOptionId");

                    b.HasIndex("PracticeTestAttemptId", "PracticeQuestionId")
                        .IsUnique();

                    b.ToTable("PracticeTestAnswers");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTestAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PracticeTestId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("TotalScore")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PracticeTestId");

                    b.HasIndex("UserId", "PracticeTestId");

                    b.ToTable("PracticeTestAttempts");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTestSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PracticeTestId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("PracticeTestId");

                    b.HasIndex("SkillId");

                    b.ToTable("PracticeTestSections");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTestSectionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PracticeTestAttemptId")
                        .HasColumnType("integer");

                    b.Property<int>("PracticeTestSectionId")
                        .HasColumnType("integer");

                    b.Property<double>("ScorePercent")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PracticeTestSectionId");

                    b.HasIndex("PracticeTestAttemptId", "PracticeTestSectionId")
                        .IsUnique();

                    b.ToTable("PracticeTestSectionResults");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ReviewItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("EaseFactor")
                        .HasColumnType("double precision");

                    b.Property<int?>("GrammarPointId")
                        .HasColumnType("integer");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("KanjiEntryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NextReviewDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Repetitions")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("VocabularyNoteEntryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrammarPointId");

                    b.HasIndex("KanjiEntryId");

                    b.HasIndex("VocabularyNoteEntryId");

                    b.HasIndex("UserId", "NextReviewDate");

                    b.ToTable("ReviewItems");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ReviewLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Quality")
                        .HasColumnType("integer");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("ReviewItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReviewItemId");

                    b.ToTable("ReviewLogs");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<int>("DailyStudyMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastStudyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StudyTimePreference")
                        .HasColumnType("text");

                    b.Property<bool>("SystemNotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("TargetJlptLevelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TargetJlptLevelId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.VocabularyEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<int>("ContentAuthorId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ExampleSentence")
                        .HasColumnType("text");

                    b.Property<string>("ExampleSentenceMeaning")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("JlptLevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Reading")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<int?>("ReviewedById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ContentAuthorId");

                    b.HasIndex("JlptLevelId");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("Word", "JlptLevelId");

                    b.ToTable("VocabularyEntries");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.VocabularyList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("VocabularyLists");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.VocabularyNoteEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("KanjiEntryId")
                        .HasColumnType("integer");

                    b.Property<string>("ManualMeaning")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ManualReading")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ManualWord")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int?>("VocabularyEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("VocabularyListId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KanjiEntryId");

                    b.HasIndex("VocabularyEntryId");

                    b.HasIndex("VocabularyListId");

                    b.ToTable("VocabularyNoteEntries");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultantAvailability", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "Consultant")
                        .WithMany("ConsultantAvailabilities")
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultant");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultationAnswer", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "Consultant")
                        .WithMany("ConsultationAnswers")
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.ConsultationRequest", "ConsultationRequest")
                        .WithOne("ConsultationAnswer")
                        .HasForeignKey("RikiPath.Domain.Entities.ConsultationAnswer", "ConsultationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultant");

                    b.Navigation("ConsultationRequest");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultationPurchase", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.ConsultationPackage", "ConsultationPackage")
                        .WithMany("Purchases")
                        .HasForeignKey("ConsultationPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("ConsultationPurchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConsultationPackage");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultationRequest", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.ConsultantAvailability", "ConsultantAvailability")
                        .WithOne("ConsultationRequest")
                        .HasForeignKey("RikiPath.Domain.Entities.ConsultationRequest", "ConsultantAvailabilityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "Consultant")
                        .WithMany("ConsultationRequestsAsConsultant")
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RikiPath.Domain.Entities.ConsultationPurchase", "ConsultationPurchase")
                        .WithOne("ConsultationRequest")
                        .HasForeignKey("RikiPath.Domain.Entities.ConsultationRequest", "ConsultationPurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultant");

                    b.Navigation("ConsultantAvailability");

                    b.Navigation("ConsultationPurchase");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.Course", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "ContentAuthor")
                        .WithMany("AuthoredCourses")
                        .HasForeignKey("ContentAuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.CourseCategory", "CourseCategory")
                        .WithMany("Courses")
                        .HasForeignKey("CourseCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.JlptLevel", "JlptLevel")
                        .WithMany("Courses")
                        .HasForeignKey("JlptLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "ReviewedBy")
                        .WithMany("ReviewedCourses")
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContentAuthor");

                    b.Navigation("CourseCategory");

                    b.Navigation("JlptLevel");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.CoursePurchase", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.Course", "Course")
                        .WithMany("Purchases")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("CoursePurchases")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.EmailVerification", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "User")
                        .WithMany("EmailVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.GradingResult", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.PracticeSubmission", "PracticeSubmission")
                        .WithOne("GradingResult")
                        .HasForeignKey("RikiPath.Domain.Entities.GradingResult", "PracticeSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticeSubmission");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.GrammarPoint", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "ContentAuthor")
                        .WithMany("AuthoredGrammarPoints")
                        .HasForeignKey("ContentAuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.JlptLevel", "JlptLevel")
                        .WithMany("GrammarPoints")
                        .HasForeignKey("JlptLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "ReviewedBy")
                        .WithMany("ReviewedGrammarPoints")
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContentAuthor");

                    b.Navigation("JlptLevel");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.KanjiEntry", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "ContentAuthor")
                        .WithMany("AuthoredKanjiEntries")
                        .HasForeignKey("ContentAuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.JlptLevel", "JlptLevel")
                        .WithMany("KanjiEntries")
                        .HasForeignKey("JlptLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "ReviewedBy")
                        .WithMany("ReviewedKanjiEntries")
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContentAuthor");

                    b.Navigation("JlptLevel");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.LearningPathSuggestion", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("LearningPathSuggestions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.Skill", "Skill")
                        .WithMany("Lessons")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.LessonGrammar", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.GrammarPoint", "GrammarPoint")
                        .WithMany("LessonGrammars")
                        .HasForeignKey("GrammarPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.Lesson", "Lesson")
                        .WithMany("LessonGrammars")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrammarPoint");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.LessonKanji", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.KanjiEntry", "KanjiEntry")
                        .WithMany("LessonKanjis")
                        .HasForeignKey("KanjiEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.Lesson", "Lesson")
                        .WithMany("LessonKanjis")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KanjiEntry");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.LessonProgress", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.Lesson", "Lesson")
                        .WithMany("LessonProgresses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("LessonProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.LessonVocabulary", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.Lesson", "Lesson")
                        .WithMany("LessonVocabularies")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.VocabularyEntry", "VocabularyEntry")
                        .WithMany("LessonVocabularies")
                        .HasForeignKey("VocabularyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("VocabularyEntry");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.Notification", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeQuestion", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.PracticeTestSection", "PracticeTestSection")
                        .WithMany("Questions")
                        .HasForeignKey("PracticeTestSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticeTestSection");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeQuestionOption", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.PracticeQuestion", "PracticeQuestion")
                        .WithMany("Options")
                        .HasForeignKey("PracticeQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticeQuestion");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeSubmission", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.JlptLevel", "JlptLevel")
                        .WithMany("PracticeSubmissions")
                        .HasForeignKey("JlptLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("PracticeSubmissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JlptLevel");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTest", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "ContentAuthor")
                        .WithMany("AuthoredPracticeTests")
                        .HasForeignKey("ContentAuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.JlptLevel", "JlptLevel")
                        .WithMany("PracticeTests")
                        .HasForeignKey("JlptLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "ReviewedBy")
                        .WithMany("ReviewedPracticeTests")
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContentAuthor");

                    b.Navigation("JlptLevel");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTestAnswer", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.PracticeQuestion", "PracticeQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("PracticeQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.PracticeTestAttempt", "PracticeTestAttempt")
                        .WithMany("Answers")
                        .HasForeignKey("PracticeTestAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.PracticeQuestionOption", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PracticeQuestion");

                    b.Navigation("PracticeTestAttempt");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTestAttempt", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.PracticeTest", "PracticeTest")
                        .WithMany("Attempts")
                        .HasForeignKey("PracticeTestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("PracticeTestAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticeTest");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTestSection", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.PracticeTest", "PracticeTest")
                        .WithMany("Sections")
                        .HasForeignKey("PracticeTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.Skill", "Skill")
                        .WithMany("PracticeTestSections")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PracticeTest");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTestSectionResult", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.PracticeTestAttempt", "PracticeTestAttempt")
                        .WithMany("SectionResults")
                        .HasForeignKey("PracticeTestAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.PracticeTestSection", "PracticeTestSection")
                        .WithMany("SectionResults")
                        .HasForeignKey("PracticeTestSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PracticeTestAttempt");

                    b.Navigation("PracticeTestSection");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ReviewItem", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.GrammarPoint", "GrammarPoint")
                        .WithMany("ReviewItems")
                        .HasForeignKey("GrammarPointId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RikiPath.Domain.Entities.KanjiEntry", "KanjiEntry")
                        .WithMany("ReviewItems")
                        .HasForeignKey("KanjiEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("ReviewItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.VocabularyNoteEntry", "VocabularyNoteEntry")
                        .WithMany("ReviewItems")
                        .HasForeignKey("VocabularyNoteEntryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("GrammarPoint");

                    b.Navigation("KanjiEntry");

                    b.Navigation("UserAccount");

                    b.Navigation("VocabularyNoteEntry");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ReviewLog", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.ReviewItem", "ReviewItem")
                        .WithMany("ReviewLogs")
                        .HasForeignKey("ReviewItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewItem");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.UserAccount", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.JlptLevel", "TargetJlptLevel")
                        .WithMany("LearnersTargeting")
                        .HasForeignKey("TargetJlptLevelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TargetJlptLevel");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.VocabularyEntry", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "ContentAuthor")
                        .WithMany("AuthoredVocabularyEntries")
                        .HasForeignKey("ContentAuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.JlptLevel", "JlptLevel")
                        .WithMany("VocabularyEntries")
                        .HasForeignKey("JlptLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "ReviewedBy")
                        .WithMany("ReviewedVocabularyEntries")
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContentAuthor");

                    b.Navigation("JlptLevel");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.VocabularyList", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("VocabularyLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.VocabularyNoteEntry", b =>
                {
                    b.HasOne("RikiPath.Domain.Entities.KanjiEntry", "KanjiEntry")
                        .WithMany("VocabularyNoteEntries")
                        .HasForeignKey("KanjiEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RikiPath.Domain.Entities.VocabularyEntry", "VocabularyEntry")
                        .WithMany("VocabularyNoteEntries")
                        .HasForeignKey("VocabularyEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RikiPath.Domain.Entities.VocabularyList", "VocabularyList")
                        .WithMany("VocabularyNoteEntries")
                        .HasForeignKey("VocabularyListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KanjiEntry");

                    b.Navigation("VocabularyEntry");

                    b.Navigation("VocabularyList");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultantAvailability", b =>
                {
                    b.Navigation("ConsultationRequest");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultationPackage", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultationPurchase", b =>
                {
                    b.Navigation("ConsultationRequest");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ConsultationRequest", b =>
                {
                    b.Navigation("ConsultationAnswer");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.Course", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.CourseCategory", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.GrammarPoint", b =>
                {
                    b.Navigation("LessonGrammars");

                    b.Navigation("ReviewItems");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.JlptLevel", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("GrammarPoints");

                    b.Navigation("KanjiEntries");

                    b.Navigation("LearnersTargeting");

                    b.Navigation("PracticeSubmissions");

                    b.Navigation("PracticeTests");

                    b.Navigation("VocabularyEntries");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.KanjiEntry", b =>
                {
                    b.Navigation("LessonKanjis");

                    b.Navigation("ReviewItems");

                    b.Navigation("VocabularyNoteEntries");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("LessonGrammars");

                    b.Navigation("LessonKanjis");

                    b.Navigation("LessonProgresses");

                    b.Navigation("LessonVocabularies");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeQuestion", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeSubmission", b =>
                {
                    b.Navigation("GradingResult");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTest", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTestAttempt", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("SectionResults");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.PracticeTestSection", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("SectionResults");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.ReviewItem", b =>
                {
                    b.Navigation("ReviewLogs");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.Skill", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("PracticeTestSections");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.UserAccount", b =>
                {
                    b.Navigation("AuthoredCourses");

                    b.Navigation("AuthoredGrammarPoints");

                    b.Navigation("AuthoredKanjiEntries");

                    b.Navigation("AuthoredPracticeTests");

                    b.Navigation("AuthoredVocabularyEntries");

                    b.Navigation("ConsultantAvailabilities");

                    b.Navigation("ConsultationAnswers");

                    b.Navigation("ConsultationPurchases");

                    b.Navigation("ConsultationRequestsAsConsultant");

                    b.Navigation("CoursePurchases");

                    b.Navigation("EmailVerifications");

                    b.Navigation("LearningPathSuggestions");

                    b.Navigation("LessonProgresses");

                    b.Navigation("Notifications");

                    b.Navigation("PracticeSubmissions");

                    b.Navigation("PracticeTestAttempts");

                    b.Navigation("ReviewItems");

                    b.Navigation("ReviewedCourses");

                    b.Navigation("ReviewedGrammarPoints");

                    b.Navigation("ReviewedKanjiEntries");

                    b.Navigation("ReviewedPracticeTests");

                    b.Navigation("ReviewedVocabularyEntries");

                    b.Navigation("VocabularyLists");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.VocabularyEntry", b =>
                {
                    b.Navigation("LessonVocabularies");

                    b.Navigation("VocabularyNoteEntries");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.VocabularyList", b =>
                {
                    b.Navigation("VocabularyNoteEntries");
                });

            modelBuilder.Entity("RikiPath.Domain.Entities.VocabularyNoteEntry", b =>
                {
                    b.Navigation("ReviewItems");
                });
#pragma warning restore 612, 618
        }
    }
}
